# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).on 'ready page:load', ->
  $('#counterpartyModalAddBtn').on 'click', ->
    counterparty_data = new Array
    counterparty_data['counterparty_name'] = $('#counterparty_counterparty_name').val()
    refreshCPList()
    return
  return

refreshCPList = ->
  $.ajax(
    method: 'POST'
    dataType: 'json'
    url: '/counterparties/'
    data: 'counterparty[counterparty_name]': $('#counterparty_counterparty_name').val()).done((msg) ->
    $.ajax(
      method: 'GET'
      dataType: 'json'
      url: '/counterparties.json').done (counterparties) ->
      selectedCP = $('#unit_category_counterparty_id option:selected').val()
      $('#counterparty_select .caret').remove()
      $('#unit_category_counterparty_id').html ''
      $('#counterparty_select').html()
      $('#unit_category_counterparty_id').append $('<option>Не указан</option>')
      $.each counterparties, (key, cp) ->
        sel = ''
        if cp.id == selectedCP
          sel = ' selected="selected"'
        $('#unit_category_counterparty_id').append $('<option ' + sel + '></option>').attr('value', cp.id).text(cp.counterparty_name)
        return
      $('select').material_select()
      $('#addCounterpartyModal').closeModal()
      $('#counterparty_counterparty_name').val ''
      return
    Materialize.toast '<i class="material-icons">info</i>&nbsp;<span>Контрагент добавлен</span>', 5000, 'rounded'
    return
  ).fail (msg) ->
    if (code = msg.responseJSON.code) == undefined
      Materialize.toast '<i class="material-icons">info</i>&nbsp;<span>Поле не может быть пустым</span>', 5000, 'rounded'
    else
      switch msg.responseJSON.code[0]
        when 900
          Materialize.toast '<i class="material-icons">info</i>&nbsp;<span>Контрагент уже существует</span>', 5000, 'rounded'
          $('#addCounterpartyModal').closeModal()
        when 901
          Materialize.toast '<i class="material-icons">info</i>&nbsp;<span>Контрагент был ранее удален</span><a class="btn-flat yellow-text" href="' + msg.responseJSON.rollback + '">Восстановить<a>', 10000, 'rounded'
          $('#addCounterpartyModal').closeModal()
    return
  return

# ---
# generated by js2coffee 2.1.0
$(document).ready ->
    # the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal()
    return
